# Generated by Django 4.0.5 on 2022-06-10 04:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todo',
            name='created_at',
            field=models.DateTimeField(default=datetime.datetime(2022, 6, 10, 4, 21, 59, 445628, tzinfo=utc)),
        ),
    ]
