# Generated by Django 4.0.5 on 2022-06-15 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0003_alter_todo_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='todo',
            name='created_at',
        ),
    ]
